# Generated by Django 4.1.2 on 2022-12-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_urls',
            field=models.JSONField(null=True),
        ),
    ]
