# Generated by Django 4.1.2 on 2023-01-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_video_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offers_min_price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offers_old_price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
